### ISSUE TITLE
Correction 

### ISSUE THREAD

**Issue by Legopapurida** [Anbarryprojects/fastapi-babel#12]
@sina-e 
When you've committed, unfortunately added pycache dir. 

I think you've forgotten to add .ignore file which cloned from the main repo.

**Comment by sina-e** [comment]
no actually, I think it was there before my commit.
output of `git log fastapi_babel/__pycache__/`

```

commit c6f9c8682ddbb293463dbaf05ce6a6fa66f41f30 (origin/development-v0)
Author: papuridalego <papuridalego@gmail.com>
Date:   Sun May 22 21:56:33 2022 +0430

     #2 First full release
```

**Comment by sina-e** [comment]
No problem, I'll fix it and create a pull request.

**Comment by Legopapurida** [comment]
I've downloaded the ignore file from github, I think the problem is for ignore file that I've downloaded. 

I'll check it out and test it

**Comment by sina-e** [comment]
there is a `__pycache__` line in Github's default `.gitignore` for python.
the ignore file is ok, I think you add and committed this before adding the ignore file.
