### ISSUE TITLE
Allow gettext's placeholders

### ISSUE THREAD

**Issue by Garito** [Anbarryprojects/fastapi-babel#44]
Hi!
In pybabel you could use _("$(name)s's house", name = "Garito")
Whould be nice to have it here

Thanks!

**Comment by Gu-f** [comment]
The other way of writing it looks good if supported...
```python
from fastapi_babel.core import lazy_gettext as _l
_l("Not support type: {mytype}").format(mytype=cls._type)
```   
But I got an error:
> AttributeError: '__LazyText' object has no attribute 'format'

**Comment by Garito** [comment]
In my mind, fastapi-babel should mimick pybabel as much as possible, otherwise should not be called fastapi-babel

**Comment by Gu-f** [comment]
> In my mind, fastapi-babel should mimick pybabel as much as possible, otherwise should not be called fastapi-babel

Is it better to mimic babel/python's original gettext? And not pybabel?

**Comment by Garito** [comment]
python gettext doesn't allow placeholders and, with fastapi-babel, one expects the pybabel api integrated as well as possible with fastapi, no?

**Comment by Legopapurida** [comment]
@Garito 
> Python gettext doesn't allow placeholders and, with fastapi-babel, one expects the pybabel API integrated as well as possible with fastapi, no?


I agree with you but we have to consider backend ecosystems like databases, forms, views, templates, and so on. 
so we have to make some APIs that work well with pybabel and Fastapi. I am working on some issues that handle all conflicts.

**Comment by Legopapurida** [comment]
> The other way of writing it looks good if supported...
> 
> ```python
> from fastapi_babel.core import lazy_gettext as _l
> _l("Not support type: {mytype}").format(mytype=cls._type)
> ```
> 
> But I got an error:
> 
> > AttributeError: '__LazyText' object has no attribute 'format'
> 
> Add one thing: gettext supports format but lazy_gettext does not, I think it should have methods supported by string objects, otherwise, it would be weird.

LazyGettext is not the main gettext, It's only a wrapper around the gettext object that when we need to apply translation texts into params without calling them explicitly like database orm fields, Wtform model fields, and ... 

so you cannot merge these two approaches and invoke them directly from the initialized object.

for example:

```python
from fastapi_babel.core import lazy_gettext as _

class Model(BaseModel):
     text: str = Field(default=_("Write what you want")
```
> model = Model()
> model.text.format()

**Comment by Legopapurida** [comment]
> Hi! In pybabel you could use _("$(name)s's house", name = "Garito") Whould be nice to have it here
> 
> Thanks!

the best approach is:

```python

name = "Parsa"
welcome_text = _("Welcome %s" % name)

```

**Comment by Garito** [comment]
If this works well with po editors and allows the normal string formatting, would be good for my part

**Comment by Legopapurida** [comment]
@Garito 
I have been many issues and please upgrade your babel

**Comment by Garito** [comment]
The new version raises this error:

```ImportError: cannot import name '_context_var' from 'fastapi_babel.core' (/usr/local/lib/python3.12/site-packages/fastapi_babel/core.py)```

Should I open a new issue?

**Comment by Legopapurida** [comment]
@Garito 

I have checked everything 

please refactor your code:

```python
from fastapi_babel import Babel, _, BabelConfigs, BabelMiddleware
from fastapi import FastAPI


app = FastAPI()
babel_config = BabelConfigs(
    __file__,
    BABEL_DEFAULT_LOCALE="en",
    BABEL_TRANSLATION_DIRECTORY="lang",
)
babel = Babel(babel_config)

app.add_middleware(BabelMiddleware, babel_configs=babel_config)

```

**Comment by Legopapurida** [comment]
uninstall previous version and install it again

**Comment by Legopapurida** [comment]
or use this 

`from fastapi_babel.local_context import context_var`
