### ISSUE TITLE
LookupError when using gettext object in global exception handler with fastapi-babel

### ISSUE THREAD

**Issue by TtBJSH** [Anbarryprojects/fastapi-babel#49]
**Description:** Hello, I encountered an issue while using fastapi-babel. In the global exception handler, when I use gettext object for translation, it raises a LookupError. My current solution is to recreate a gettext object, but I'm wondering if there's a better approach. Should I change the way global exception handling is implemented, or is there a better way to use the gettext object from context_var in the global exception handler?  Can you give me some advice？

**Here’s my current approach:**
```python
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    log.error(f"Exception occurred: {exc}")
    
    # Check if translation context exists
    if context_var.get(None) is None:
        lang_code = request.headers.get("Accept-Language", 'en')
        temp_babel = babel  
        temp_babel.locale = get_language(lang_code)  
        _ = temp_babel.gettext  # Create a new gettext object
    
    message = _('Service Unavailable')  # This raises a LookupError
    
    return JSONResponse(
        status_code=500,
        content={"message": message}
    )```

**Comment by legobatman1378** [comment]
@TtBJSH 

```python

from fastapi_babel import BabelContext, use_babel, _

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    log.error(f"Exception occurred: {exc}")
    babel = use_babel(request) or Babel(babel_config)
    # Check if translation context exists
    with BabelContext(babel_configs, babel=babel):
          message = _('Service Unavailable')  # This raises a LookupError
          return JSONResponse(
               status_code=500,
               content={"message": message}
    )
```

**Comment by legobatman1378** [comment]
@TtBJSH

But I don't think you need any new babel customization 
when you are in request scope you will access to gettext.

**Comment by TtBJSH** [comment]
> @TtBJSH
> 
> 但是我认为当您在请求范围内访问 gettext 时，您不需要任何新的 babel 定制。
现在我尝试在中间件里进行异常捕获，你是对的，一开始我没有完全理解ContextVard的传递机制，非常感谢您的回复

**Comment by TtBJSH** [comment]
> @TtBJSH
> 
> 但是我认为当您在请求范围内访问 gettext 时，您不需要任何新的 babel 定制。

Now I am trying to catch exceptions in the middleware, and you are right. At first, I did not fully understand the passing mechanism of ContextVard. Thank you very much for your reply


> @TtBJSH
> 
> But I don't think you need any new babel customization when you are in request scope you will access to gettext.



> @TtBJSH
> 
> But I don't think you need any new babel customization when you are in request scope you will access to gettext.

Now I am trying to catch exceptions in the middleware, and you are right. At first, I did not fully understand the passing mechanism of ContextVard. Thank you very much for your reply
