### ISSUE TITLE
Add strict formatting and linting, maybe with pre-commit?

### ISSUE THREAD

**Issue by sina-e** [Anbarryprojects/fastapi-babel#7]
on my first pull request #6 I noticed that the code is not formatted properly, imports are not sorted, and it seems a little inconsistent.

suggestion:

add flake8, black, and isort to the dev requirements. also, pre-commit to format and lint the code.

**Comment by sina-e** [comment]
I think it's better to set up a dev environment. take a look at [PyTitle](https://github.com/pytitle/PyTitle)

**Comment by Legopapurida** [comment]
Oh right, in this first step we will add stub file for adding type hints, because of python type hint versions we may face with type hint errors in gunicorn web server ( we struggled on it ). 

So having a stub file can improve our code healthy.

**Comment by Legopapurida** [comment]
Also we will add black instead of flake8. 
Black is much more standard than flake8 as we used.

**Comment by sina-e** [comment]
I think is best to use black and flake8 together, Black for code formatting, flake8 for linting. also isort for sorting the imports. take a look at this [article](https://rohitgupta.xyz/blog/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort/).

**Comment by Legopapurida** [comment]
@sina-e 
I will check this out.
thanks to you.

**Comment by sina-e** [comment]
> Oh right, in this first step we will add stub file for adding type hints, because of python type hint versions we may face with type hint errors in gunicorn web server ( we struggled on it ).

what sort of problems did you have with gunicorn and type hinting? (i wasn't talking about type hinting in the original issue, but I'm curious) I didn't see any problems in my last projects.

**Comment by Legopapurida** [comment]
Python type hint versions 
3.10 has difference with 3.7 type hinting.
