### ISSUE TITLE
Add automatic tests

### ISSUE THREAD

**Issue by sina-e** [Anbarryprojects/fastapi-babel#8]
setup automatic tests, with pytest and tox.

also, I think GitHub-actions would be a good option for testing in different environments.

**Comment by Legopapurida** [comment]
Yes, I'll do that as soon as possible

**Comment by deeplook** [comment]
> setup automatic tests, with pytest and tox.
> 
> also, I think GitHub-actions would be a good option for testing in different environments.

Hell yah... ;-)
